# Generated by Django 5.0.1 on 2024-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_userform_name_alter_userform_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userform',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
